### PR TITLE
Verify network of lightning invoice & addresses

### LINKED ISSUE #270: Fail invoices that are on a different network

### PR DESCRIPTION
**Pull request by benthecarman**
Closes #270

### CODE REVIEW

File: node-manager/src/nodemanager.rs [hunk 1]
```diff
@@ -455,11 +456,13 @@ impl NodeManager {
...
-        match self
-            .wallet
-            .send(destination_address, amount, fee_rate)
-            .await
-        {
+        let send_to = Address::from_str(&destination_address)?;
+
+        if send_to.network != self.network {
+            return Err(MutinyJsError::IncorrectNetwork);
+        }
```
Comment (TonyGiorgio) [inline node-manager/src/nodemanager.rs:463]: `sweep_wallet` and `check_address` should probably have this check too, right?

**Review by TonyGiorgio — CHANGES_REQUESTED** [review]

File: node-manager/src/nodemanager.rs (hunk 1 above)
Comment (benthecarman) [reply node-manager/src/nodemanager.rs:463]: Added

**Review by TonyGiorgio — APPROVED** [review]
